import { vehicles } from "@/data/vehicles";
import type { Vehicle } from "@/types/vehicle";

export const locales = ["ka", "ru", "en"] as const;
export type Locale = (typeof locales)[number];
export const DEFAULT_LOCALE: Locale = "ka";
export const LOCALE_STORAGE_KEY = "zecar-locale";
export const isLocale = (value: unknown): value is Locale => typeof value === "string" && locales.includes(value as Locale);

const en = {
  localeNames: { ka: "ქართული", ru: "Русский", en: "English" },
  common: { skip: "Skip to content", call: "Call", whatsapp: "WhatsApp", loading: "Loading inventory…", miles: "mi", priceOnRequest: "Price on request", detailsPending: "Details to be confirmed" },
  heroImageAlt: "Chevrolet Trailblazer RS on the road",
  pageTitles: { home: "ZECAR — Premium pre-owned cars", cars: "Cars", about: "About", contact: "Contact", notFound: "Page not found" },
  nav: { home: "Home", cars: "Cars", about: "About", contact: "Contact", primary: "Primary navigation", mobile: "Mobile navigation", openMenu: "Open menu", closeMenu: "Close menu", brandHome: "ZECAR home", language: "Choose language", callShowroom: "Call showroom" },
  footer: { explore: "Explore", contact: "Contact", hours: "Opening hours", copyright: "Sample showroom experience.", demo: "Inventory shown is demonstration content." },
  dealership: { tagline: "Considered cars. Clearly presented.", description: "A modern independent showroom for carefully presented pre-owned vehicles.", address: "100 Motor Row, Your City", hours: ["Mon–Fri · 09:00–18:00", "Saturday · 10:00–16:00", "Sunday · By appointment"] },
  home: {
    heroEyebrow: "Independent automotive showroom", heroTitle: "Drive something\nworth choosing.", heroCopy: "Carefully presented pre-owned vehicles, clear details, and direct conversation from first look to showroom visit.", heroAlt: "Chevrolet Trailblazer RS on the road", viewCars: "View cars", callUs: "Call us", selected: "Selected inventory",
    featuredEyebrow: "Featured selection", featuredTitle: "Cars chosen to be considered.", featuredCopy: "A focused preview from our replaceable sample inventory, with the information you need up front.", explore: "Explore full inventory",
    clearEyebrow: "What you’ll find", clearTitle: "Cars and useful information in one place.", principles: [["Photo gallery", "See every available vehicle from several angles."], ["Key details", "Review the information currently available for each car."], ["Simple search", "Find vehicles by make, model, and practical filters."], ["Direct contact", "Call or message us directly about a specific vehicle."]],
    latestEyebrow: "Latest inventory", latestTitle: "Recently added.", viewAll: "View all cars", processEyebrow: "From screen to showroom", processTitle: "A simple four-step process.", process: [["Browse", "Search the complete inventory and compare practical specifications."], ["Inspect", "Open the gallery, review equipment, and read the full listing."], ["Talk", "Call or message us about the exact vehicle you are considering."], ["Visit", "Arrange a convenient showroom visit directly with our team."]],
    ctaEyebrow: "Start a conversation", ctaTitle: "Found something\nyou want to see?", ctaCopy: "Speak directly with the showroom about availability, specifications, or arranging a visit.", contact: "Contact ZECAR",
  },
  inventory: { eyebrow: "Current selection", title: "Find your next car.", copy: "Search, filter, and compare our carefully presented sample inventory.", filterTitle: "Filter inventory", filtersLabel: "Inventory filters", search: "Search make or model", searchPlaceholder: "e.g. Lexus NX 200 F Sport", make: "Make", yearFrom: "Year from", priceUpTo: "Price up to", mileageUpTo: "Mileage up to", fuel: "Fuel", transmission: "Transmission", body: "Body", availability: "Availability", all: "All", anyYear: "Any year", anyPrice: "Any price", anyMileage: "Any mileage", resetAll: "Reset all filters", vehicle: "vehicle", vehicles: "vehicles", filters: "Filters", sortLabel: "Sort vehicles", sort: { newest: "Newest listings", priceAsc: "Price: low to high", priceDesc: "Price: high to low", year: "Year: newest", mileage: "Mileage: lowest" }, noMatches: "No matches", emptyTitle: "Let’s widen the search.", emptyCopy: "Try clearing one or more filters to see the available sample inventory.", reset: "Reset filters", close: "Close filters", show: "Show" },
  card: { featured: "Featured", newArrival: "New arrival", viewDetails: "View details", viewVehicle: "View", askWhatsapp: "Ask about", exteriorView: "exterior view" },
  detail: { cars: "Cars", aboutEyebrow: "About this car", overview: "Overview", equipment: "Equipment", features: "Key features", interested: "Interested in this car?", askAbout: "Ask about the", inquiryCopy: "Contact the showroom directly. Your message will reference this exact listing.", whatsappInquiry: "WhatsApp inquiry", emailInquiry: "Email inquiry", keepLooking: "Keep looking", similar: "Similar vehicles.", allCars: "All cars", specs: { vin: "VIN", mileage: "Mileage", fuel: "Fuel", transmission: "Transmission", engine: "Engine", body: "Body", drivetrain: "Drivetrain", exterior: "Exterior", interior: "Interior", location: "Location" } },
  gallery: { fullscreen: "View full screen", previous: "Previous image", next: "Next image", show: "Show image", dialog: "image gallery", close: "Close gallery", image: "view" },
  about: { eyebrow: "About ZECAR", title: "A showroom built around clarity.", intro: "We believe choosing a car should begin with good information and a straightforward conversation.", imageAlt: "Modern premium vehicle presented in a clean setting", approach: "Our approach", approachTitle: "Considered, useful, direct.", paragraphs: ["ZECAR is a demonstration of a modern independent automotive showroom. It is designed to help drivers browse a focused selection, understand each vehicle, and contact a real person without being pushed through an online purchase funnel.", "Every listing follows the same clear structure: multiple images, practical specifications, visible status, and contact actions tied to the exact car. The sample vehicles currently shown are replaceable content and do not represent live stock."], values: [["Present with care", "Photography and details should let each car speak for itself."], ["Say what matters", "Useful specifications are more valuable than inflated claims."], ["Keep it human", "Questions deserve a direct answer by phone, message, or email."]], cta: "See what’s currently in the showroom.", browse: "Browse cars" },
  contact: { eyebrow: "Contact", title: "Let’s talk cars.", intro: "Ask about a vehicle, request more detail, or get in touch before visiting the showroom.", callMessage: "Call or message", showroom: "Showroom", placeholder: "Replace this placeholder address before launch.", hours: "Opening hours", send: "Send an inquiry", explanation: "Complete the form and your email app will open with the message ready for your review." },
  form: { name: "Name", email: "Email", phone: "Phone", optional: "optional", message: "Message", defaultMessage: "I’m interested in the {vehicle}. Please confirm its availability.", submit: "Open email to send", prepared: "Submitting opens your email app with this message prepared. Nothing is sent automatically.", opened: "Your email app should now be open. Please review and send the message there." },
  notFound: { eyebrow: "404", title: "This page isn’t here.", copy: "The vehicle or page you requested may have moved or is no longer available.", home: "Return home", cars: "Browse cars" },
  inquiry: { greeting: "Hello ZECAR, I’m interested in the", listing: "Listing", availableQuestion: "Is it still available?", subjectVehicle: "Inquiry", subjectShowroom: "Showroom inquiry", name: "Name", email: "Email", phone: "Phone", vehicle: "Vehicle", message: "Message" },
  enums: { fuel: { Petrol: "Petrol", Diesel: "Diesel", Hybrid: "Hybrid", Electric: "Electric" }, transmission: { Automatic: "Automatic", Manual: "Manual" }, body: { SUV: "SUV", Sedan: "Sedan", Coupe: "Coupe", Wagon: "Wagon" }, drivetrain: { FWD: "FWD", RWD: "RWD", AWD: "AWD" }, condition: { "Pre-owned": "Pre-owned" }, availability: { Available: "Available", Reserved: "Reserved", "Recently Sold": "Recently Sold" } },
};
export type Dictionary = typeof en;

const ka = {
  heroImageAlt: "Chevrolet Trailblazer RS გზაზე",
  localeNames: { ka: "ქართული", ru: "Русский", en: "English" }, common: { skip: "შინაარსზე გადასვლა", call: "დარეკვა", whatsapp: "WhatsApp", loading: "ავტომობილები იტვირთება…", miles: "მილი", priceOnRequest: "ფასი მოთხოვნით", detailsPending: "დეტალები დასაზუსტებელია" }, pageTitles: { home: "ZECAR — პრემიუმ მეორადი ავტომობილები", cars: "ავტომობილები", about: "ჩვენ შესახებ", contact: "კონტაქტი", notFound: "გვერდი ვერ მოიძებნა" },
  nav: { home: "მთავარი", cars: "ავტომობილები", about: "ჩვენ შესახებ", contact: "კონტაქტი", primary: "მთავარი ნავიგაცია", mobile: "მობილური ნავიგაცია", openMenu: "მენიუს გახსნა", closeMenu: "მენიუს დახურვა", brandHome: "ZECAR-ის მთავარი გვერდი", language: "ენის არჩევა", callShowroom: "შოურუმში დარეკვა" },
  footer: { explore: "ნავიგაცია", contact: "კონტაქტი", hours: "სამუშაო საათები", copyright: "სადემონსტრაციო შოურუმი.", demo: "წარმოდგენილი მარაგი სადემონსტრაციოა." }, dealership: { tagline: "შერჩეული ავტომობილები. მკაფიო ინფორმაცია.", description: "თანამედროვე დამოუკიდებელი შოურუმი ყურადღებით წარმოდგენილი მეორადი ავტომობილებისთვის.", address: "100 Motor Row, Your City", hours: ["ორშ–პარ · 09:00–18:00", "შაბათი · 10:00–16:00", "კვირა · წინასწარი შეთანხმებით"] },
  home: { heroEyebrow: "დამოუკიდებელი ავტომობილების შოურუმი", heroTitle: "მართეთ ავტომობილი,\nრომლის არჩევაც ღირს.", heroCopy: "ყურადღებით წარმოდგენილი მეორადი ავტომობილები, მკაფიო დეტალები და პირდაპირი კომუნიკაცია პირველივე ნახვიდან შოურუმში ვიზიტამდე.", viewCars: "ავტომობილების ნახვა", callUs: "დაგვირეკეთ", selected: "შერჩეული მარაგი", featuredEyebrow: "რჩეული კოლექცია", featuredTitle: "ავტომობილები გააზრებული არჩევანისთვის.", featuredCopy: "ჩვენი განახლებადი სადემონსტრაციო მარაგის მოკლე მიმოხილვა — ყველა მნიშვნელოვანი ინფორმაციით.", explore: "სრული მარაგის ნახვა", clearEyebrow: "რას ნახავთ ZECAR-ზე", clearTitle: "ავტომობილები და საჭირო ინფორმაცია ერთ სივრცეში.", principles: [["ფოტოგალერეა", "ნახეთ თითოეული ხელმისაწვდომი ავტომობილი სხვადასხვა რაკურსით."], ["ძირითადი მონაცემები", "გაეცანით ამ ეტაპზე ხელმისაწვდომ ინფორმაციას თითოეულ ავტომობილზე."], ["მარტივი ძიება", "იპოვეთ ავტომობილი მარკის, მოდელისა და პრაქტიკული ფილტრების მიხედვით."], ["პირდაპირი კონტაქტი", "დაგვირეკეთ ან მოგვწერეთ კონკრეტულ ავტომობილთან დაკავშირებით."]], latestEyebrow: "უახლესი მარაგი", latestTitle: "ახლახან დამატებული.", viewAll: "ყველა ავტომობილის ნახვა", processEyebrow: "ეკრანიდან შოურუმამდე", processTitle: "მარტივი ოთხსაფეხურიანი პროცესი.", process: [["დაათვალიერეთ", "მოძებნეთ სრულ მარაგში და შეადარეთ პრაქტიკული მახასიათებლები."], ["შეამოწმეთ", "გახსენით გალერეა, გაეცანით აღჭურვილობასა და სრულ აღწერას."], ["დაგვიკავშირდით", "დაგვირეკეთ ან მოგვწერეთ ზუსტად იმ ავტომობილის შესახებ, რომელსაც განიხილავთ."], ["გვესტუმრეთ", "ჩვენს გუნდთან შეთანხმებით დაგეგმეთ შოურუმში ვიზიტი თქვენთვის მოსახერხებელ დროს."]], ctaEyebrow: "დაიწყეთ საუბარი", ctaTitle: "იპოვეთ ავტომობილი,\nრომლის ნახვაც გსურთ?", ctaCopy: "ხელმისაწვდომობის, მახასიათებლების ან ვიზიტის დაგეგმვისთვის პირდაპირ დაუკავშირდით შოურუმს.", contact: "დაუკავშირდით ZECAR-ს" },
  inventory: { eyebrow: "მიმდინარე არჩევანი", title: "იპოვეთ თქვენი შემდეგი ავტომობილი.", copy: "მოძებნეთ, გაფილტრეთ და შეადარეთ ჩვენი ყურადღებით წარმოდგენილი სადემონსტრაციო მარაგი.", filterTitle: "მარაგის გაფილტვრა", filtersLabel: "ავტომობილების ფილტრები", search: "მარკის ან მოდელის ძიება", searchPlaceholder: "მაგ. Lexus NX 200 F Sport", make: "მარკა", yearFrom: "წელი — დან", priceUpTo: "ფასი — მდე", mileageUpTo: "გარბენი — მდე", fuel: "საწვავი", transmission: "გადაცემათა კოლოფი", body: "ძარის ტიპი", availability: "ხელმისაწვდომობა", all: "ყველა", anyYear: "ნებისმიერი წელი", anyPrice: "ნებისმიერი ფასი", anyMileage: "ნებისმიერი გარბენი", resetAll: "ყველა ფილტრის გასუფთავება", vehicle: "ავტომობილი", vehicles: "ავტომობილი", filters: "ფილტრები", sortLabel: "ავტომობილების დალაგება", sort: { newest: "უახლესი განცხადებები", priceAsc: "ფასი: ზრდადობით", priceDesc: "ფასი: კლებადობით", year: "წელი: უახლესი", mileage: "გარბენი: უმცირესი" }, noMatches: "შედეგი ვერ მოიძებნა", emptyTitle: "გავაფართოოთ ძიება.", emptyCopy: "ხელმისაწვდომი სადემონსტრაციო მარაგის სანახავად გაასუფთავეთ ერთი ან რამდენიმე ფილტრი.", reset: "ფილტრების გასუფთავება", close: "ფილტრების დახურვა", show: "ჩვენება:" },
  card: { featured: "რჩეული", newArrival: "ახალი შემოსული", viewDetails: "დეტალების ნახვა", viewVehicle: "ნახვა:", askWhatsapp: "WhatsApp-ით კითხვა:", exteriorView: "ექსტერიერი" }, detail: { cars: "ავტომობილები", aboutEyebrow: "ამ ავტომობილის შესახებ", overview: "მიმოხილვა", equipment: "აღჭურვილობა", features: "ძირითადი ფუნქციები", interested: "დაინტერესდით ამ ავტომობილით?", askAbout: "იკითხეთ მოდელზე", inquiryCopy: "პირდაპირ დაუკავშირდით შოურუმს. შეტყობინებაში ზუსტად ეს განცხადება იქნება მითითებული.", whatsappInquiry: "WhatsApp-ით კითხვა", emailInquiry: "ელფოსტით კითხვა", keepLooking: "განაგრძეთ ძიება", similar: "მსგავსი ავტომობილები.", allCars: "ყველა ავტომობილი", specs: { vin: "VIN", mileage: "გარბენი", fuel: "საწვავი", transmission: "გადაცემათა კოლოფი", engine: "ძრავა", body: "ძარის ტიპი", drivetrain: "წამყვანი თვლები", exterior: "ექსტერიერი", interior: "ინტერიერი", location: "მდებარეობა" } },
  gallery: { fullscreen: "სრულ ეკრანზე ნახვა", previous: "წინა სურათი", next: "შემდეგი სურათი", show: "სურათის ჩვენება", dialog: "ფოტოგალერეა", close: "გალერეის დახურვა", image: "ხედი" }, about: { eyebrow: "ZECAR-ის შესახებ", title: "შოურუმი, რომლის საფუძველიც სიცხადეა.", intro: "გვჯერა, რომ ავტომობილის არჩევა სრულყოფილი ინფორმაციითა და გულწრფელი საუბრით უნდა იწყებოდეს.", imageAlt: "თანამედროვე პრემიუმ ავტომობილი სუფთა გარემოში", approach: "ჩვენი მიდგომა", approachTitle: "გააზრებული, სასარგებლო, პირდაპირი.", paragraphs: ["ZECAR თანამედროვე დამოუკიდებელი ავტომობილების შოურუმის სადემონსტრაციო ვერსიაა. ის მძღოლებს ეხმარება დაათვალიერონ მიზნობრივად შერჩეული ავტომობილები, კარგად გაიცნონ თითოეული მათგანი და ონლაინ შეძენის თავსმოხვეული პროცესის გარეშე დაუკავშირდნენ რეალურ ადამიანს.", "ყველა განცხადება ერთნაირ, მკაფიო სტრუქტურას მიჰყვება: მრავალი ფოტო, პრაქტიკული მახასიათებლები, ხილული სტატუსი და ზუსტად ამ ავტომობილთან დაკავშირებული საკონტაქტო მოქმედებები. წარმოდგენილი ავტომობილები განახლებადი სადემონსტრაციო მასალაა და რეალურ მარაგს არ ასახავს."], values: [["წარმოადგინეთ ყურადღებით", "ფოტოებმა და დეტალებმა თითოეულ ავტომობილს საკუთარი ისტორიის გადმოცემის საშუალება უნდა მისცეს."], ["თქვით მთავარი", "სასარგებლო მახასიათებლები გადაჭარბებულ დაპირებებზე ბევრად ღირებულია."], ["შეინარჩუნეთ ადამიანური ურთიერთობა", "ყველა კითხვას ეკუთვნის პირდაპირი პასუხი — ტელეფონით, შეტყობინებით ან ელფოსტით."]], cta: "ნახეთ, რა არის ამჟამად შოურუმში.", browse: "ავტომობილების ნახვა" },
  contact: { eyebrow: "კონტაქტი", title: "ვისაუბროთ ავტომობილებზე.", intro: "იკითხეთ ავტომობილის შესახებ, მოითხოვეთ დამატებითი დეტალები ან ვიზიტამდე დაგვიკავშირდით.", callMessage: "დარეკეთ ან მოგვწერეთ", showroom: "შოურუმი", placeholder: "გაშვებამდე ჩაანაცვლეთ ეს დროებითი მისამართი.", hours: "სამუშაო საათები", send: "მოთხოვნის გაგზავნა", explanation: "შეავსეთ ფორმა და თქვენს ელფოსტის აპში გასაგზავნად მომზადებული შეტყობინება გაიხსნება." }, form: { name: "სახელი", email: "ელფოსტა", phone: "ტელეფონი", optional: "არასავალდებულო", message: "შეტყობინება", defaultMessage: "მაინტერესებს {vehicle}. გთხოვთ, დამიდასტუროთ მისი ხელმისაწვდომობა.", submit: "ელფოსტის გახსნა გასაგზავნად", prepared: "ფორმის გაგზავნა თქვენს ელფოსტის აპში მომზადებულ შეტყობინებას გახსნის. ავტომატურად არაფერი იგზავნება.", opened: "ელფოსტის აპი გახსნილი უნდა იყოს. გთხოვთ, გადაამოწმოთ და იქიდან გაგზავნოთ შეტყობინება." }, notFound: { eyebrow: "404", title: "ეს გვერდი ვერ მოიძებნა.", copy: "მოთხოვნილი ავტომობილი ან გვერდი შესაძლოა გადატანილია ან აღარ არის ხელმისაწვდომი.", home: "მთავარ გვერდზე დაბრუნება", cars: "ავტომობილების ნახვა" }, inquiry: { greeting: "გამარჯობა, ZECAR. მაინტერესებს", listing: "განცხადება", availableQuestion: "კვლავ ხელმისაწვდომია?", subjectVehicle: "მოთხოვნა", subjectShowroom: "მოთხოვნა შოურუმისთვის", name: "სახელი", email: "ელფოსტა", phone: "ტელეფონი", vehicle: "ავტომობილი", message: "შეტყობინება" }, enums: { fuel: { Petrol: "ბენზინი", Diesel: "დიზელი", Hybrid: "ჰიბრიდი", Electric: "ელექტრო" }, transmission: { Automatic: "ავტომატური", Manual: "მექანიკური" }, body: { SUV: "SUV", Sedan: "სედანი", Coupe: "კუპე", Wagon: "უნივერსალი" }, drivetrain: { FWD: "წინა", RWD: "უკანა", AWD: "სრული" }, condition: { "Pre-owned": "მეორადი" }, availability: { Available: "ხელმისაწვდომია", Reserved: "დაჯავშნილია", "Recently Sold": "ახლახან გაიყიდა" } },
} as Dictionary;

const ru = {
  ...en,
  heroImageAlt: "Chevrolet Trailblazer RS на дороге",
  pageTitles: { home: "ZECAR — Премиальные автомобили с пробегом", cars: "Автомобили", about: "О нас", contact: "Контакты", notFound: "Страница не найдена" },
  common: { skip: "Перейти к содержимому", call: "Позвонить", whatsapp: "WhatsApp", loading: "Автомобили загружаются…", miles: "миль" }, nav: { home: "Главная", cars: "Автомобили", about: "О нас", contact: "Контакты", primary: "Основная навигация", mobile: "Мобильная навигация", openMenu: "Открыть меню", closeMenu: "Закрыть меню", brandHome: "Главная ZECAR", language: "Выбрать язык", callShowroom: "Позвонить в салон" }, footer: { explore: "Навигация", contact: "Контакты", hours: "Часы работы", copyright: "Демонстрационный автосалон.", demo: "Представленный ассортимент является демонстрационным." }, dealership: { tagline: "Продуманный выбор. Ясная подача.", description: "Современный независимый салон тщательно представленных автомобилей с пробегом.", address: "100 Motor Row, Your City", hours: ["Пн–Пт · 09:00–18:00", "Суббота · 10:00–16:00", "Воскресенье · по записи"] },
  home: { heroEyebrow: "Независимый автомобильный салон", heroTitle: "Выбирайте автомобиль,\nкоторый стоит водить.", heroCopy: "Тщательно представленные автомобили с пробегом, ясные сведения и прямое общение — от первого просмотра до визита в салон.", viewCars: "Смотреть автомобили", callUs: "Позвонить нам", selected: "Избранный ассортимент", featuredEyebrow: "Избранная подборка", featuredTitle: "Автомобили для взвешенного выбора.", featuredCopy: "Краткий обзор нашего обновляемого демонстрационного ассортимента со всей важной информацией.", explore: "Смотреть весь ассортимент", clearEyebrow: "Что есть на ZECAR", clearTitle: "Автомобили и полезная информация в одном месте.", principles: [["Фотогалерея", "Посмотрите каждый доступный автомобиль с разных ракурсов."], ["Основные данные", "Ознакомьтесь с доступной информацией по каждому автомобилю."], ["Простой поиск", "Найдите автомобиль по марке, модели и практичным фильтрам."], ["Прямая связь", "Позвоните или напишите нам по поводу конкретного автомобиля."]], latestEyebrow: "Новые поступления", latestTitle: "Добавлены недавно.", viewAll: "Все автомобили", processEyebrow: "От экрана до салона", processTitle: "Четыре простых шага.", process: [["Выберите", "Изучите полный ассортимент и сравните практические характеристики."], ["Осмотрите", "Откройте галерею, изучите оснащение и полное описание."], ["Свяжитесь", "Позвоните или напишите по поводу именно того автомобиля, который рассматриваете."], ["Приезжайте", "Согласуйте с нашей командой удобное время визита в салон."]], ctaEyebrow: "Начните разговор", ctaTitle: "Нашли автомобиль,\nкоторый хотите увидеть?", ctaCopy: "Свяжитесь с салоном напрямую, чтобы уточнить доступность, характеристики или договориться о визите.", contact: "Связаться с ZECAR" },
  inventory: { eyebrow: "Текущая подборка", title: "Найдите свой следующий автомобиль.", copy: "Ищите, фильтруйте и сравнивайте наш тщательно представленный демонстрационный ассортимент.", filterTitle: "Фильтры", filtersLabel: "Фильтры автомобилей", search: "Марка или модель", searchPlaceholder: "например, Lexus NX 200 F Sport", make: "Марка", yearFrom: "Год от", priceUpTo: "Цена до", mileageUpTo: "Пробег до", fuel: "Топливо", transmission: "Коробка передач", body: "Кузов", availability: "Статус", all: "Все", anyYear: "Любой год", anyPrice: "Любая цена", anyMileage: "Любой пробег", resetAll: "Сбросить все фильтры", vehicle: "автомобиль", vehicles: "автомобилей", filters: "Фильтры", sortLabel: "Сортировать автомобили", sort: { newest: "Сначала новые объявления", priceAsc: "Цена: по возрастанию", priceDesc: "Цена: по убыванию", year: "Год: сначала новые", mileage: "Пробег: сначала меньший" }, noMatches: "Ничего не найдено", emptyTitle: "Расширим поиск.", emptyCopy: "Сбросьте один или несколько фильтров, чтобы увидеть доступный демонстрационный ассортимент.", reset: "Сбросить фильтры", close: "Закрыть фильтры", show: "Показать" },
  card: { featured: "Избранное", newArrival: "Новое поступление", viewDetails: "Подробнее", viewVehicle: "Смотреть", askWhatsapp: "Спросить в WhatsApp о", exteriorView: "вид снаружи" }, detail: { cars: "Автомобили", aboutEyebrow: "Об автомобиле", overview: "Обзор", equipment: "Оснащение", features: "Основные опции", interested: "Заинтересовал автомобиль?", askAbout: "Узнайте о", inquiryCopy: "Свяжитесь с салоном напрямую. В сообщении будет указано именно это объявление.", whatsappInquiry: "Запрос в WhatsApp", emailInquiry: "Запрос по email", keepLooking: "Продолжить поиск", similar: "Похожие автомобили.", allCars: "Все автомобили", specs: { vin: "VIN", mileage: "Пробег", fuel: "Топливо", transmission: "Коробка передач", engine: "Двигатель", body: "Кузов", drivetrain: "Привод", exterior: "Цвет кузова", interior: "Салон", location: "Местонахождение" } }, gallery: { fullscreen: "На весь экран", previous: "Предыдущее изображение", next: "Следующее изображение", show: "Показать изображение", dialog: "фотогалерея", close: "Закрыть галерею", image: "ракурс" },
  about: { eyebrow: "О ZECAR", title: "Салон, построенный на ясности.", intro: "Мы верим, что выбор автомобиля должен начинаться с полной информации и честного разговора.", imageAlt: "Современный премиальный автомобиль в чистой обстановке", approach: "Наш подход", approachTitle: "Продуманно, полезно, прямо.", paragraphs: ["ZECAR — демонстрация современного независимого автомобильного салона. Он помогает водителям изучить тщательно отобранные автомобили, понять каждый из них и связаться с реальным человеком без навязанной воронки онлайн-покупки.", "Все объявления устроены одинаково ясно: несколько фотографий, практические характеристики, заметный статус и способы связи по конкретному автомобилю. Представленные образцы можно заменить; они не отражают реальный склад."], values: [["Представлять бережно", "Фотографии и детали должны позволять автомобилю говорить за себя."], ["Говорить по существу", "Полезные характеристики ценнее громких обещаний."], ["Оставаться людьми", "Вопросы заслуживают прямого ответа по телефону, в сообщении или по email."]], cta: "Посмотрите, что сейчас представлено в салоне.", browse: "Смотреть автомобили" }, contact: { eyebrow: "Контакты", title: "Поговорим об автомобилях.", intro: "Спросите об автомобиле, запросите подробности или свяжитесь с нами перед визитом.", callMessage: "Позвонить или написать", showroom: "Автосалон", placeholder: "Замените этот временный адрес перед запуском.", hours: "Часы работы", send: "Отправить запрос", explanation: "Заполните форму, и в вашем почтовом приложении откроется готовое к проверке сообщение." }, form: { name: "Имя", email: "Email", phone: "Телефон", optional: "необязательно", message: "Сообщение", defaultMessage: "Меня интересует {vehicle}. Пожалуйста, подтвердите его доступность.", submit: "Открыть письмо", prepared: "Форма откроет подготовленное сообщение в почтовом приложении. Автоматически ничего не отправляется.", opened: "Почтовое приложение должно быть открыто. Проверьте и отправьте сообщение оттуда." }, notFound: { eyebrow: "404", title: "Такой страницы нет.", copy: "Запрошенный автомобиль или страница могли быть перемещены либо больше недоступны.", home: "На главную", cars: "Смотреть автомобили" }, inquiry: { greeting: "Здравствуйте, ZECAR. Меня интересует", listing: "Объявление", availableQuestion: "Он ещё доступен?", subjectVehicle: "Запрос", subjectShowroom: "Запрос в автосалон", name: "Имя", email: "Email", phone: "Телефон", vehicle: "Автомобиль", message: "Сообщение" }, enums: { fuel: { Petrol: "Бензин", Diesel: "Дизель", Hybrid: "Гибрид", Electric: "Электро" }, transmission: { Automatic: "Автоматическая", Manual: "Механическая" }, body: { SUV: "SUV", Sedan: "Седан", Coupe: "Купе", Wagon: "Универсал" }, drivetrain: { FWD: "Передний", RWD: "Задний", AWD: "Полный" }, condition: { "Pre-owned": "С пробегом" }, availability: { Available: "В наличии", Reserved: "Зарезервирован", "Recently Sold": "Недавно продан" } },
} as Dictionary;

ru.common.priceOnRequest = "Цена по запросу";
ru.common.detailsPending = "Детали уточняются";
ka.home.heroAlt = "Chevrolet Trailblazer RS გზაზე";
ru.home.heroAlt = "Chevrolet Trailblazer RS на дороге";

export const dictionaries: Record<Locale, Dictionary> = { ka, ru, en };
export const getDictionary = (locale: unknown) => dictionaries[isLocale(locale) ? locale : DEFAULT_LOCALE];

type LocalizedVehicle = { description: string; features: string[]; engine: string; exteriorColor: string; interiorColor: string; location: string };
const enVehicles: Record<string, LocalizedVehicle> = Object.fromEntries(vehicles.map((vehicle) => [vehicle.id, { description: vehicle.description, features: vehicle.features, engine: vehicle.engine ?? "", exteriorColor: vehicle.exteriorColor, interiorColor: vehicle.interiorColor ?? "", location: vehicle.location }]));
const v = (description: string, features: string[], engine: string | null, exteriorColor: string, interiorColor: string | null): LocalizedVehicle => ({ description, features, engine: engine ?? "", exteriorColor, interiorColor: interiorColor ?? "", location: "ZECAR Main Showroom" });
export const localizedVehicles: Record<Locale, Record<string, LocalizedVehicle>> = {
  en: enVehicles,
  ka: {
    "zec-001": v("2021 წლის სექტემბერში წარმოებული Chevrolet Trailblazer RS, 1.3L ძრავით, 88,000 მილის გარბენითა და წინა წამყვანი თვლებით. ფირუზისფერი კონტრასტული შავი სახურავით.", ["1.3L ძრავა", "88,000 მილი", "წინა წამყვანი თვლები"], "1.3L", "ფირუზისფერი, შავი სახურავით", null),
    "zec-002": v("ვერცხლისფერი 2016 წლის Lexus NX 200 F Sport, 2.0L ძრავითა და წინა წამყვანი თვლებით.", ["2.0L ძრავა", "წინა წამყვანი თვლები"], "2.0L", "ვერცხლისფერი", null),
    "zec-003": v("2023 წლის Nissan Kicks SR, 1.6L ძრავითა და 27,000 მილის გარბენით. მარგალიტისფერი თეთრი კონტრასტული შავი სახურავით.", ["1.6L ძრავა", "27,000 მილი"], "1.6L", "მარგალიტისფერი თეთრი, შავი სახურავით", null),
    "zec-004": v("2022 წლის აპრილში წარმოებული Kia Soul, 2.0L ძრავითა და 63,000 მილის გარბენით. მუქი წითელი ფერის.", ["2.0L ძრავა", "63,000 მილი"], "2.0L", "მუქი წითელი", null),
    "zec-005": v("2018 წლის Hyundai Santa Fe 2.0T, 2.0L ტურბო ძრავით, შავი ფერის.", ["2.0L ტურბო ძრავა"], "2.0L ტურბო", "შავი", null),

  },
  ru: {
    "zec-001": v("Chevrolet Trailblazer RS 2021 года, выпущенный в сентябре 2021 года, с двигателем 1.3L, пробегом 88 000 миль и передним приводом. Бирюзовый с контрастной чёрной крышей.", ["Двигатель 1.3L", "88 000 миль", "Передний привод"], "1.3L", "Бирюзовый с чёрной крышей", null),
    "zec-002": v("Серебристый Lexus NX 200 F Sport 2016 года с двигателем 2.0L и передним приводом.", ["Двигатель 2.0L", "Передний привод"], "2.0L", "Серебристый", null),
    "zec-003": v("Nissan Kicks SR 2023 года с двигателем 1.6L и пробегом 27 000 миль. Жемчужно-белый с контрастной чёрной крышей.", ["Двигатель 1.6L", "27 000 миль"], "1.6L", "Жемчужно-белый с чёрной крышей", null),
    "zec-004": v("Kia Soul 2022 года, выпущенный в апреле 2022 года, с двигателем 2.0L и пробегом 63 000 миль. Тёмно-красного цвета.", ["Двигатель 2.0L", "63 000 миль"], "2.0L", "Тёмно-красный", null),
    "zec-005": v("Hyundai Santa Fe 2.0T 2018 года с турбодвигателем 2.0L, чёрного цвета.", ["Турбодвигатель 2.0L"], "2.0L турбо", "Чёрный", null),

  },
};

Object.values(localizedVehicles.ka).forEach((content) => { content.location = "ZECAR-ის მთავარი შოურუმი"; });
Object.values(localizedVehicles.ru).forEach((content) => { content.location = "Главный салон ZECAR"; });

export function vehicleContent(vehicle: Vehicle, locale: Locale): LocalizedVehicle {
  if (locale === "en") return { description: vehicle.description, features: vehicle.features, engine: vehicle.engine ?? "", exteriorColor: vehicle.exteriorColor, interiorColor: vehicle.interiorColor ?? "", location: vehicle.location };
  return localizedVehicles[locale][vehicle.id];
}
