import Image from "next/image";
import Link from "next/link";
import { Arrow, Check, Phone } from "@/components/icons";
import { SectionHeading } from "@/components/section-heading";
import { VehicleCard } from "@/components/vehicle-card";
import { dealership } from "@/data/dealership";
import { vehicles } from "@/data/vehicles";

export default function HomePage() {
  const featured = vehicles.filter((v) => v.featured).slice(0, 3);
  return <>
    <section className="hero"><Image src={vehicles[0].coverImage} alt="Silver performance coupe outside a modern showroom" fill sizes="100vw" priority /><div className="hero-shade" /><div className="shell hero-content"><p className="eyebrow light-text">Independent automotive showroom</p><h1>Drive something<br />worth choosing.</h1><p>Carefully presented pre-owned vehicles, clear details, and direct conversation from first look to showroom visit.</p><div className="hero-actions"><Link className="button light-button" href="/cars">View cars <Arrow className="icon" /></Link><a className="button ghost-light" href={`tel:${dealership.phoneHref}`}><Phone className="icon" /> Call us</a></div></div><div className="hero-index"><span>Selected inventory</span><span>01 / 06</span></div></section>
    <section className="section shell"><SectionHeading eyebrow="Featured selection" title="Cars chosen to be considered." copy="A focused preview from our replaceable sample inventory, with the information you need up front." /><div className="three-grid">{featured.map((vehicle, index) => <VehicleCard key={vehicle.id} vehicle={vehicle} priority={index === 0} />)}</div><Link className="text-link" href="/cars">Explore full inventory <Arrow className="icon" /></Link></section>
    <section className="statement-section"><div className="shell statement-grid"><div><p className="eyebrow">A clearer way to browse</p><h2>Details first.<br />Pressure never.</h2></div><div className="principles">{[["Careful presentation", "Each listing is organized to make condition, character, and key details easy to understand."], ["Multiple photographs", "Inspect each vehicle through a considered gallery before deciding whether to visit."], ["Clear information", "Specifications, availability, and pricing are displayed without unnecessary friction."], ["Direct communication", "Speak to the showroom by phone, WhatsApp, or a vehicle-specific email inquiry."]].map(([title, copy], i) => <div key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section>
    <section className="section shell"><div className="split-heading"><SectionHeading eyebrow="Latest inventory" title="Recently added." /><Link className="text-link" href="/cars">View all cars <Arrow className="icon" /></Link></div><div className="three-grid">{vehicles.slice().sort((a,b) => b.createdDate.localeCompare(a.createdDate)).slice(0,3).map((vehicle) => <VehicleCard key={vehicle.id} vehicle={vehicle} />)}</div></section>
    <section className="process-section"><div className="shell"><SectionHeading eyebrow="From screen to showroom" title="A simple four-step process." /><div className="process-grid">{[["01", "Browse", "Search the complete inventory and compare practical specifications."], ["02", "Inspect", "Open the gallery, review equipment, and read the full listing."], ["03", "Talk", "Call or message us about the exact vehicle you are considering."], ["04", "Visit", "Arrange a convenient showroom visit directly with our team."]].map(([number, title, copy]) => <div key={number}><span>{number}</span><Check className="icon" /><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section>
    <section className="cta-section"><div className="shell cta-inner"><div><p className="eyebrow light-text">Start a conversation</p><h2>Found something<br />you want to see?</h2></div><div><p>Speak directly with the showroom about availability, specifications, or arranging a visit.</p><div><Link className="button light-button" href="/contact">Contact ZECAR <Arrow className="icon" /></Link><a href={`tel:${dealership.phoneHref}`}>{dealership.phone}</a></div></div></div></section>
  </>;
}
