"use client";
import { usePathname } from "next/navigation"; import { useEffect } from "react"; import { classifyClick } from "@/lib/analytics";
const VISITOR="zecar_visitor_id",CREATED="zecar_visitor_created_at",SESSION="zecar_session_id",SEEN="zecar_seen",MAX_AGE=90*86_400_000;
let lastPage="",lastPageAt=0;
export function analyticsUuid(){return globalThis.crypto?.randomUUID?.()??"10000000-1000-4000-8000-100000000000".replace(/[018]/g,c=>(Number(c)^crypto.getRandomValues(new Uint8Array(1))[0]&15>>Number(c)/4).toString(16))}
export function browserId(storage:Pick<Storage,"getItem"|"setItem"|"removeItem">,now=Date.now()){let id=storage.getItem(VISITOR);const created=Number(storage.getItem(CREATED));const returning=Boolean(id)&&Number.isFinite(created)&&now-created<MAX_AGE;if(!returning){id=analyticsUuid();storage.setItem(VISITOR,id);storage.setItem(CREATED,String(now))}return{id:id!,returning}}
function device(){const width=window.innerWidth;return width<768?"mobile":width<1024?"tablet":"desktop"}
function privacyEnabled(){return navigator.doNotTrack==="1"||(navigator as Navigator&{globalPrivacyControl?:boolean}).globalPrivacyControl===true}
function send(event_name:string,path:string,link_kind?:string){try{if(privacyEnabled()||path.startsWith("/admin"))return;const visitor=browserId(localStorage);let session=sessionStorage.getItem(SESSION);if(!session){session=analyticsUuid();sessionStorage.setItem(SESSION,session)}const firstPage=event_name==="page_view"&&!sessionStorage.getItem(SEEN);if(firstPage)sessionStorage.setItem(SEEN,"1");const vehicle=/^\/cars\/([a-z0-9-]+)$/.exec(path)?.[1];let referrer_host:null|string=null;if(firstPage&&document.referrer)try{referrer_host=new URL(document.referrer).hostname}catch{}const body=JSON.stringify({event_id:analyticsUuid(),event_name,path,visitor_id:visitor.id,session_id:session,vehicle_slug:vehicle||null,referrer_host,locale:document.documentElement.lang||"unknown",device_class:device(),metadata:{...(firstPage?{return_visitor:visitor.returning}:{}),...(link_kind?{link_kind}:{})}});if(navigator.sendBeacon&&navigator.sendBeacon("/api/analytics/events",new Blob([body],{type:"application/json"})))return;void fetch("/api/analytics/events",{method:"POST",headers:{"content-type":"application/json"},body,keepalive:true}).catch(()=>{})}catch{}}
export function AnalyticsTracker(){const pathname=usePathname();useEffect(()=>{document.documentElement.lang="ka";const now=Date.now();if(lastPage===pathname&&now-lastPageAt<1000)return;lastPage=pathname;lastPageAt=now;send("page_view",pathname);if(/^\/cars\/[a-z0-9-]+$/.test(pathname))send("vehicle_view",pathname)},[pathname]);useEffect(()=>{const click=(event:MouseEvent)=>{const target=(event.target as Element)?.closest?.("a") as HTMLAnchorElement|null;if(!target)return;const kind=classifyClick(target.href,location.origin);if(kind)send(kind.eventName,location.pathname,kind.linkKind)};const inquiry=()=>send("contact_click",location.pathname,"inquiry");document.addEventListener("click",click,{capture:true});document.addEventListener("zecar:inquiry-submitted",inquiry);return()=>{document.removeEventListener("click",click,{capture:true});document.removeEventListener("zecar:inquiry-submitted",inquiry)}},[]);return null}
