import type { Metadata } from "next";
import { NotFoundView, VehicleView } from "@/components/localized-pages";
import { dealership } from "@/data/dealership";
import { vehicles } from "@/data/vehicles";
import { localizedVehicles } from "@/lib/i18n";
import { formatMileage, getVehicleBySlug, getVehicleTitle } from "@/lib/vehicles";

export function generateStaticParams(){return vehicles.map(({slug})=>({slug}))}
export const dynamicParams=false;
export async function generateMetadata({params}:PageProps<"/cars/[slug]">):Promise<Metadata>{const vehicle=getVehicleBySlug((await params).slug);if(!vehicle)return{title:"ავტომობილი ვერ მოიძებნა",robots:{index:false,follow:false}};const title=getVehicleTitle(vehicle);const known=[vehicle.mileage!==null?formatMileage(vehicle.mileage,"ka","მილი"):null,vehicle.fuelType,vehicle.transmission].filter(Boolean).join(", ");return{title,description:known?`${known}. იხილეთ ${title}-ის ფოტოები და დეტალები.`:`${title} — დეტალები დასაზუსტებელია. დაგვიკავშირდით მახასიათებლებისა და ფასის შესახებ.`,alternates:{canonical:`/cars/${vehicle.slug}`},openGraph:{title,description:localizedVehicles.ka[vehicle.id].description,images:[{url:vehicle.coverImage,alt:title}]}}}
export default async function VehiclePage({params}:PageProps<"/cars/[slug]">){const vehicle=getVehicleBySlug((await params).slug);if(!vehicle)return <NotFoundView/>;const content=localizedVehicles.ka[vehicle.id];const title=getVehicleTitle(vehicle);const jsonLd:Record<string,unknown>={"@context":"https://schema.org","@type":"Vehicle",name:title,image:vehicle.galleryImages,description:content.description,manufacturer:{"@type":"Organization",name:vehicle.make},model:vehicle.model,color:content.exteriorColor,url:`${dealership.siteUrl}/cars/${vehicle.slug}`};if(vehicle.year!==null)jsonLd.vehicleModelDate=String(vehicle.year);if(vehicle.vin)jsonLd.vehicleIdentificationNumber=vehicle.vin;if(vehicle.mileage!==null)jsonLd.mileageFromOdometer={"@type":"QuantitativeValue",value:vehicle.mileage,unitCode:"SMI"};if(vehicle.fuelType)jsonLd.fuelType=vehicle.fuelType;if(vehicle.transmission)jsonLd.vehicleTransmission=vehicle.transmission;if(vehicle.price!==null)jsonLd.offers={"@type":"Offer",price:vehicle.price,priceCurrency:vehicle.currency,availability:vehicle.availabilityStatus==="Available"?"https://schema.org/InStock":"https://schema.org/LimitedAvailability",url:`${dealership.siteUrl}/cars/${vehicle.slug}`};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,"\\u003c")}}/><VehicleView vehicle={vehicle}/></>}
